version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  ms-auth:
    build: ./ms-auth
    container_name: ms_auth
    restart: always
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce
      JWT_SECRET: supersecreto
    depends_on:
      - postgres
    networks:
      - ecommerce_net

  ms-products:
    build: ./ms-products
    container_name: ms_products
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce
    depends_on:
      - postgres
    networks:
      - ecommerce_net

  ms-orders:
    build: ./ms-orders
    container_name: ms_orders
    restart: always
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce
    depends_on:
      - postgres
    networks:
      - ecommerce_net

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      JWT_SECRET: supersecreto
    depends_on:
      - ms-auth
      - ms-products
      - ms-orders
    networks:
      - ecommerce_net

networks:
  ecommerce_net:
    driver: bridge

volumes:
  postgres_data: